name: Build webconfig Component for Coverity

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop, cov ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop, cov ]

jobs:
  build-utopia-on-pr:
    name: Build utopia component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install the dependent packages
      - name: Install packages
        run: |
          apt-get update
          apt-get install -y cmake
          apt-get -y install libcunit1 libcunit1-dev libmsgpack-dev libtool xsltproc docbook-xsl-ns uuid-dev libcurl4-openssl-dev lcov libmsgpack* libcjson-dev build-essential
          pip3 install cmake --upgrade

      - name: Make Build Directory
        run: mkdir build

      - name: CMake
        working-directory: build
        run: |
          cmake .. -DWEBCONFIG_BIN_SUPPORT:BOOL=true -DWAN_FAILOVER_SUPPORTED:BOOL=true

      - name: Coverity run
        working-directory: build
        run: |
          ps aux
          cmake --version
          make 

      - name: native build
        run: |
          # Trust the workspace
          git config --global --add safe.directory '*'
          # Pull the latest changes for the native build system
          git submodule update --init --recursive --remote
          # Build and install dependencies
          chmod +x build_tools_workflows/cov_docker_script/setup_dependencies.sh
          ./build_tools_workflows/cov_docker_script/setup_dependencies.sh ./cov_docker_script/component_config.json
          # Build component
          chmod +x build_tools_workflows/cov_docker_script/build_native.sh
          ./build_tools_workflows/cov_docker_script/build_native.sh ./cov_docker_script/component_config.json "$(pwd)"
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
